config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'
  
  resources :users

  resources :topics
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/topic_controller.rb
class TopicController < ApplicationController
end

app/controllers/user_controller.rb
class UserController < ApplicationController

	def index
	end

	def new
	end

	def create
	end

	def show
	end
	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topic_helper.rb
module TopicHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Discourseapi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/topic/index.html.erb
<h1>Listing Topics</h1>
 

<%= link_to 'Back', 'welcome/index' %>


#Form search by User


<table>
  <tr>
    <th>Topics</th>
    <th></th>
  </tr>



  <%latest_topics.each do |index| %>
    <tr>
      <td><%= link_to latest_topics.title, topics_path %></td>
    </tr>
  <% end %>
</table>

app/views/topic/show.html.erb
<p>
  <strong>FirstName:</strong>
  <%= @users.firstname %>
</p>
 
<p>
  <strong>LastName:</strong>
  <%= @users.lastname %>
</p>




<table>
  

#Using the API get array of users

  <% @users.each do |index| %>
    <tr>
      <td><%= index.usernamename%></td>
      <td> commented </td>
      <td><%= index.post_count %></td>
      <td>times</td>
      <td><%= link_to 'Show', users_path(index) %></td>
    </tr>
  <% end %>
</table>


<%= link_to 'Back', topics_path %>

app/views/user/index.html.erb
<h1>Listing users</h1>
 

<%= link_to 'Back', 'welcome/index' %>


#Form search by User

<%= form_with scope: :users, url: user_path, local: true do |form| %>
  <p>
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </p>
 
  <p>
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>




<table>
  <tr>
    <th>Students</th>
    <th></th>
  </tr>

#Using the API get array of users

  <% @users.each do |index| %>
    <tr>
      <td><%= index.firstname %></td>
      <td><%= index.lastname %></td>
      <td><%= link_to 'Show', users_path(index) %></td>
    </tr>
  <% end %>
</table>

app/views/user/show.html.erb
<p>
  <strong>FirstName:</strong>
  <%= @users.firstname %>
</p>
 
<p>
  <strong>LastName:</strong>
  <%= @users.lastname %>
</p>


<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Welcome to API testing</h1>

<%= link_to 'Track comments on topics', 'topic/index'%>

<%= link_to 'Track Student Data', 'user/index'%>